Attribute VB_Name = "Module1"
Public GlobalUserName As String
Public GlobalPassword As String
Public GlobalArray() As String
Public Flag As Integer
Public MyValue As Single
Public VarQuizCompositeKey As String
Public VarStudentUsername As String
Public VarQuizScore As Integer
Public VarQuestionSequence As String
Public StudentQuizArrangement As Integer
Public GlobalStudentPassword As String
Public GlobalItemNumber As Integer
Public varTimeCounter As Integer
Public GlobalGoTimeCounter As Integer
Public GlobalMessageFlag As Integer
Public globalSendList1 As String
Public IdleTime As Integer
